 $(document).ready(function(){
 $('.dropright-submenu a.test').on('mouseenter',function(e){
$(this).next('ul').toggle(); 

  });
$("#ds a").css("color" ,"DodgerBlue");
$(".column3").show();
$(".col31").hide();
$(".col32").show();
$(".column31").hide();
$(".column4").hide();
$(".column41").hide();
$(".col41").hide();
$(".col42").hide();
$(".column5").hide();
$(".column51").hide();
$(".col51").hide();
$(".col52").hide();
$(".column6").hide();
$(".column61").hide();
$(".col61").hide();
$(".col62").hide();
$(".column7").hide();
$(".column71").hide();
$(".col71").hide();
$(".col72").hide();
$(".column8").hide();
$(".column81").hide();
$(".col81").hide();
$(".col82").hide();
$(".but").click(function(){
 location.reload(true);
});

$(".col32").click(function(){
$(".column3").hide();
$(".column31").show();
$(".col31").show();
$(".col32").hide();
$(".column41").hide();
$(".col41").hide();
$(".col42").hide();
$(".column5").hide();
$(".column51").hide();
$(".col51").hide();
$(".col52").hide();
$(".column6").hide();
$(".column61").hide();
$(".col61").hide();
$(".col62").hide();
$(".column7").hide();
$(".column71").hide();
$(".col71").hide();
$(".col72").hide();
$(".column8").hide();
$(".column81").hide();
$(".col81").hide();
$(".col82").hide();
event.preventDefault();
$.scrollTo($('.column31'), 1000);
});
$(".col31").click(function(){
$(".column31").hide();
$(".column3").show();
$(".col32").show();
$(".col31").hide();
$(".column41").hide();
$(".col41").hide();
$(".col42").hide();
$(".column5").hide();
$(".column51").hide();
$(".col51").hide();
$(".col52").hide();
$(".column6").hide();
$(".column61").hide();
$(".col61").hide();
$(".col62").hide();
$(".column7").hide();
$(".column71").hide();
$(".col71").hide();
$(".col72").hide();
$(".column8").hide();
$(".column81").hide();
$(".col81").hide();
$(".col82").hide();
event.preventDefault();
$.scrollTo($('.column3'), 1000);
});
$(".col42").click(function(){
$(".column4").hide();
$(".column41").show();
$(".col41").show();
$(".col42").hide();
$(".column31").hide();
$(".column3").hide();
$(".col31").hide();
$(".col32").hide();
$(".column5").hide();
$(".column51").hide();
$(".col51").hide();
$(".col52").hide();
$(".column6").hide();
$(".column61").hide();
$(".col61").hide();
$(".col62").hide();
$(".column7").hide();
$(".column71").hide();
$(".col71").hide();
$(".col72").hide();
$(".column8").hide();
$(".column81").hide();
$(".col81").hide();
$(".col82").hide();
event.preventDefault();
$.scrollTo($('.column41'), 1000);
});
$(".col41").click(function(){
$(".column41").hide();
$(".column4").show();
$(".col42").show();
$(".col41").hide();
$(".column31").hide();
$(".column3").hide();
$(".col31").hide();
$(".col32").hide();
$(".column5").hide();
$(".column51").hide();
$(".col51").hide();
$(".col52").hide();
$(".column6").hide();
$(".column61").hide();
$(".col61").hide();
$(".col62").hide();
$(".column7").hide();
$(".column71").hide();
$(".col71").hide();
$(".col72").hide();
$(".column8").hide();
$(".column81").hide();
$(".col81").hide();
$(".col82").hide();
event.preventDefault();
$.scrollTo($('.column4'), 1000);
});


$(".col52").click(function(){
$(".column5").hide();
$(".column51").show();
$(".col51").show();
$(".col52").hide();
$(".column41").hide();
$(".column4").hide();
$(".col41").hide();
$(".col42").hide();
$(".column3").hide();
$(".column31").hide();
$(".col31").hide();
$(".col32").hide();
$(".column6").hide();
$(".column61").hide();
$(".col61").hide();
$(".col62").hide();
$(".column7").hide();
$(".column71").hide();
$(".col71").hide();
$(".col72").hide();
$(".column8").hide();
$(".column81").hide();
$(".col81").hide();
$(".col82").hide();
event.preventDefault();
$.scrollTo($('.column51'), 1000);
});
$(".col51").click(function(){
$(".column51").hide();
$(".column5").show();
$(".col52").show();
$(".col51").hide();
$(".column41").hide();
$(".column4").hide();
$(".col41").hide();
$(".col42").hide();
$(".column3").hide();
$(".column31").hide();
$(".col31").hide();
$(".col32").hide();
$(".column6").hide();
$(".column61").hide();
$(".col61").hide();
$(".col62").hide();
$(".column7").hide();
$(".column71").hide();
$(".col71").hide();
$(".col72").hide();
$(".column8").hide();
$(".column81").hide();
$(".col81").hide();
$(".col82").hide();
event.preventDefault();
$.scrollTo($('.column5'), 1000);
});


$(".col62").click(function(){
$(".column6").hide();
$(".column61").show();
$(".col61").show();
$(".col62").hide();
$(".column41").hide();
$(".column4").hide();
$(".col41").hide();
$(".col42").hide();
$(".column5").hide();
$(".column51").hide();
$(".col51").hide();
$(".col52").hide();
$(".column3").hide();
$(".column31").hide();
$(".col31").hide();
$(".col32").hide();
$(".column7").hide();
$(".column71").hide();
$(".col71").hide();
$(".col72").hide();
$(".column8").hide();
$(".column81").hide();
$(".col81").hide();
$(".col82").hide();
event.preventDefault();
$.scrollTo($('.column61'), 1000);
});
$(".col61").click(function(){
$(".column61").hide();
$(".column6").show();
$(".col62").show();
$(".col61").hide();
$(".column41").hide();
$(".column4").hide();
$(".col41").hide();
$(".col42").hide();
$(".column5").hide();
$(".column51").hide();
$(".col51").hide();
$(".col52").hide();
$(".column3").hide();
$(".column31").hide();
$(".col31").hide();
$(".col32").hide();
$(".column7").hide();
$(".column71").hide();
$(".col71").hide();
$(".col72").hide();
$(".column8").hide();
$(".column81").hide();
$(".col81").hide();
$(".col82").hide();
event.preventDefault();
$.scrollTo($('.column6'), 1000);
});


$(".col72").click(function(){
$(".column7").hide();
$(".column71").show();
$(".col71").show();
$(".col72").hide();
$(".column41").hide();
$(".column4").hide();
$(".col41").hide();
$(".col42").hide();
$(".column5").hide();
$(".column51").hide();
$(".col51").hide();
$(".col52").hide();
$(".column6").hide();
$(".column61").hide();
$(".col61").hide();
$(".col62").hide();
$(".column3").hide();
$(".column31").hide();
$(".col31").hide();
$(".col32").hide();
$(".column8").hide();
$(".column81").hide();
$(".col81").hide();
$(".col82").hide();
event.preventDefault();
$.scrollTo($('.column71'), 1000);
});
$(".col71").click(function(){
$(".column71").hide();
$(".column7").show();
$(".col72").show();
$(".col71").hide();
$(".column41").hide();
$(".column4").hide();
$(".col41").hide();
$(".col42").hide();
$(".column5").hide();
$(".column51").hide();
$(".col51").hide();
$(".col52").hide();
$(".column6").hide();
$(".column61").hide();
$(".col61").hide();
$(".col62").hide();
$(".column3").hide();
$(".column31").hide();
$(".col31").hide();
$(".col32").hide();
$(".column8").hide();
$(".column81").hide();
$(".col81").hide();
$(".col82").hide();
event.preventDefault();
$.scrollTo($('.column7'), 1000);
});


$(".col82").click(function(){
$(".column8").hide();
$(".column81").show();
$(".col81").show();
$(".col82").hide();
$(".column41").hide();
$(".column4").hide();
$(".col41").hide();
$(".col42").hide();
$(".column5").hide();
$(".column51").hide();
$(".col51").hide();
$(".col52").hide();
$(".column6").hide();
$(".column61").hide();
$(".col61").hide();
$(".col62").hide();
$(".column7").hide();
$(".column71").hide();
$(".col71").hide();
$(".col72").hide();
$(".column3").hide();
$(".column31").hide();
$(".col31").hide();
$(".col32").hide();
event.preventDefault();
$.scrollTo($('.column81'), 1000);
});
$(".col81").click(function(){
$(".column81").hide();
$(".column8").show();
$(".col82").show();
$(".col81").hide();
$(".column41").hide();
$(".column4").hide();
$(".col41").hide();
$(".col42").hide();
$(".column5").hide();
$(".column51").hide();
$(".col51").hide();
$(".col52").hide();
$(".column6").hide();
$(".column61").hide();
$(".col61").hide();
$(".col62").hide();
$(".column7").hide();
$(".column71").hide();
$(".col71").hide();
$(".col72").hide();
$(".column3").hide();
$(".column31").hide();
$(".col31").hide();
$(".col32").hide();
event.preventDefault();
$.scrollTo($('.column8'), 1000);
});

$("#ds").click(function(){
$("#ds a").css("color","DodgerBlue");
$("#ai a").css("color","black");
$("#as a").css("color","black");
$("#pro a").css("color","black");
$("#cc a").css("color","black");
$("#bus a").css("color","black");
$(".column31").hide();
$(".col31").hide();
$(".col32").show();
$(".column4").hide();
$(".column41").hide();
$(".col41").hide();
$(".col42").hide();
$(".column5").hide();
$(".column51").hide();
$(".col51").hide();
$(".col52").hide();
$(".column6").hide();
$(".column61").hide();
$(".col61").hide();
$(".col62").hide();
$(".column7").hide();
$(".column71").hide();
$(".col71").hide();
$(".col72").hide();
$(".column8").hide();
$(".column81").hide();
$(".col81").hide();
$(".col82").hide();
$(".column3").show();
event.preventDefault();
$.scrollTo($('.column3'), 1000);
  }); 
  $("#ai").click(function(){
$("#ds a").css("color","black");
$("#ai a").css("color","DodgerBlue");
$("#as a").css("color","black");
$("#pro a").css("color","black");
$("#cc a").css("color","black");
$("#bus a").css("color","black");
$(".column4").show();
$(".column41").hide();
$(".col42").show();
$(".col41").hide();
$(".column3").hide();
$(".column31").hide();
$(".col32").hide();
$(".col31").hide();
$(".column5").hide();
$(".column51").hide();
$(".col51").hide();
$(".col52").hide();
$(".column6").hide();
$(".column61").hide();
$(".col61").hide();
$(".col62").hide();
$(".column7").hide();
$(".column71").hide();
$(".col71").hide();
$(".col72").hide();
$(".column8").hide();
$(".column81").hide();
$(".col81").hide();
$(".col82").hide();
event.preventDefault();
$.scrollTo($('.column4'), 1000);
  });
  $("#pro").click(function(){
$("#ds a").css("color","black");
$("#ai a").css("color","black");
$("#as a").css("color","black");
$("#pro a").css("color","DodgerBlue");
$("#cc a").css("color","black");
$("#bus a").css("color","black");
$(".column3").hide();
$(".column31").hide();
$(".col31").hide();
$(".col32").hide();
$(".column4").hide();
$(".column41").hide();
$(".col41").hide();
$(".col42").hide();
$(".column6").hide();
$(".column61").hide();
$(".col61").hide();
$(".col62").hide();
$(".column7").hide();
$(".column71").hide();
$(".col71").hide();
$(".col72").hide();
$(".column8").hide();
$(".column81").hide();
$(".col81").hide();
$(".col82").hide();
$(".col51").hide();
$(".col52").show();
$(".column5").show();
 $(".column51").hide();
event.preventDefault();
$.scrollTo($('.column5'), 1000);
  });
$("#as").click(function(){
$("#ds a").css("color","black");
$("#ai a").css("color","black");
$("#as a").css("color","DodgerBlue");
$("#pro a").css("color","black");
$("#cc a").css("color","black");
$("#bus a").css("color","black");
$(".column3").hide();
$(".column31").hide();
$(".col31").hide();
$(".col32").hide();
$(".column4").hide();
$(".column41").hide();
$(".col41").hide();
$(".col42").hide();
$(".column5").hide();
$(".column51").hide();
$(".col51").hide();
$(".col52").hide();
$(".column7").hide();
$(".column71").hide();
$(".col71").hide();
$(".col72").hide();
$(".column8").hide();
$(".column81").hide();
$(".col81").hide();
$(".col82").hide();
$(".col61").hide();
$(".col62").show();
$(".column61").hide();
 $(".column6").show();
event.preventDefault();
$.scrollTo($('.column6'), 1000);
  });
 $("#cc").click(function(){
$("#ds a").css("color","black");
$("#ai a").css("color","black");
$("#as a").css("color","black");
$("#pro a").css("color","black");
$("#cc a").css("color","DodgerBlue");
$("#bus a").css("color","black");
$(".column3").hide();
$(".column31").hide();
$(".col31").hide();
$(".col32").hide();
$(".column4").hide();
$(".column41").hide();
$(".col41").hide();
$(".col42").hide();
$(".column5").hide();
$(".column51").hide();
$(".col51").hide();
$(".col52").hide();
$(".column6").hide();
$(".column61").hide();
$(".col61").hide();
$(".col62").hide();
$(".column8").hide();
$(".column81").hide();
$(".col81").hide();
$(".col82").hide();
$(".column7").show();
$(".column71").hide();
$(".col71").hide();
$(".col72").show();
event.preventDefault();
$.scrollTo($('.column7'), 1000);
  });
  $("#bus").click(function(){
$("#ds a").css("color","black");
$("#ai a").css("color","black");
$("#as a").css("color","black");
$("#pro a").css("color","black");
$("#cc a").css("color","black");
$("#bus a").css("color","DodgerBlue");
$(".column3").hide();
$(".column31").hide();
$(".col31").hide();
$(".col32").hide();
$(".column4").hide();
$(".column41").hide();
$(".col41").hide();
$(".col42").hide();
$(".column5").hide();
$(".column51").hide();
$(".col51").hide();
$(".col52").hide();
$(".column6").hide();
$(".column61").hide();
$(".col61").hide();
$(".col62").hide();
$(".column7").hide();
$(".column71").hide();
$(".col71").hide();
$(".col72").hide();
$(".column8").show();
$(".column81").hide();
$(".col81").hide();
$(".col82").show();
event.preventDefault();
$.scrollTo($('.column8'), 1000);
  });
});
